@extends('layouts.app')
@section('title', 'Press releases')
@section('page', 'releases')
@section('content')
<div id="releases-app" data-index-url="{{ route('press-releases.index') }}">
    <div class="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="eyebrow">Copy desk</p><h1 class="page-title mt-2">Press releases</h1><p class="lede mt-3 max-w-2xl">Draft the news, cut the fog, and keep every version in its proper drawer.</p></div><button class="button-primary" type="button" data-release-create>Write a release</button></div>
    <div class="panel-flat"><div class="grid gap-3 border-b border-stone-400 p-4 sm:grid-cols-[1fr_14rem]"><div><label class="label" for="release-search">Search copy</label><input class="field" id="release-search" placeholder="Search headlines…"></div><div><label class="label" for="release-folder-filter">Drawer</label><select class="field" id="release-folder-filter"><option value="">All drawers</option>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->folder_name }}</option>@endforeach</select></div></div><div class="overflow-x-auto"><table class="w-full min-w-[46rem]"><thead><tr class="table-head"><th class="p-4">Headline</th><th class="p-4">Drawer</th><th class="p-4">Last revised</th><th class="p-4 text-right">Actions</th></tr></thead><tbody id="release-rows" class="divide-y divide-stone-300 dark:divide-stone-700"></tbody></table></div><div id="release-pagination" class="border-t border-stone-400 p-4"></div></div>
</div>
<dialog id="release-dialog" class="modal"><form id="release-form" class="modal-body"><input name="id" type="hidden"><div class="flex items-start justify-between"><div><p class="eyebrow">Copy desk</p><h2 class="mt-2 text-2xl font-black" data-modal-title>Write a release</h2></div><button class="button-quiet" type="button" data-dialog-close>Close</button></div><div class="mt-6 space-y-5"><div><label class="label" for="release-subject">Headline</label><input class="field" id="release-subject" name="subject" required></div><div><label class="label" for="release-folder">Drawer</label><select class="field" id="release-folder" name="folder_id" required>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->folder_name }}</option>@endforeach</select></div><div><label class="label" for="release-content">Release copy</label><textarea class="field" id="release-content" name="content" rows="12" required></textarea></div><div id="release-errors" class="field-error"></div><button class="button-primary" type="submit">Save release</button></div></form></dialog>
@endsection
