@extends('layouts.app')
@section('title', 'Newsrooms')
@section('page', 'newsrooms')
@section('content')
<div id="newsrooms-app" data-index-url="{{ route('news-rooms.index') }}" data-public-base="{{ route('newsroom.public', auth()->user()->newsroom_slug) }}">
    <div class="mb-9 flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p class="eyebrow">Public archive</p><h1 class="page-title mt-2">Newsrooms</h1><p class="lede mt-3 max-w-2xl">Give reporters a clean, permanent place to find your current story and the record behind it.</p></div><button class="button-primary" type="button" data-room-create>New newsroom story</button></div>
    <div class="mb-6 max-w-md"><label class="label" for="room-search">Search newsroom stories</label><input class="field" id="room-search" placeholder="Search headlines…"></div><div id="room-cards" class="grid gap-5 md:grid-cols-2 xl:grid-cols-3"></div><div id="room-pagination" class="mt-8"></div>
</div>
<dialog id="room-dialog" class="modal"><form id="room-form" class="modal-body"><input name="id" type="hidden"><div class="flex items-start justify-between"><div><p class="eyebrow">Public archive</p><h2 class="mt-2 text-2xl font-black" data-modal-title>New newsroom story</h2></div><button class="button-quiet" type="button" data-dialog-close>Close</button></div><div class="mt-6 grid gap-5 sm:grid-cols-2"><div class="sm:col-span-2"><label class="label" for="room-subject">Headline</label><input class="field" id="room-subject" name="subject" required></div><div><label class="label" for="room-folder">Drawer</label><select class="field" id="room-folder" name="folder_id" required>@foreach($folders as $folder)<option value="{{ $folder->id }}">{{ $folder->folder_name }}</option>@endforeach</select></div><div><label class="label" for="room-date">Publication date</label><input class="field" id="room-date" name="date" type="date"></div><div class="sm:col-span-2"><label class="label" for="room-image">Featured image URL</label><input class="field" id="room-image" name="featured_image" type="url" placeholder="https://…"></div><div class="sm:col-span-2"><label class="label" for="room-summary">Summary</label><textarea class="field" id="room-summary" name="summary" rows="3"></textarea></div><div class="sm:col-span-2"><label class="label" for="room-content">Story</label><textarea class="field" id="room-content" name="content" rows="10" required></textarea></div><div id="room-errors" class="field-error sm:col-span-2"></div><button class="button-primary sm:col-span-2" type="submit">Save newsroom story</button></div></form></dialog>
@endsection
