const csrf = document.querySelector('meta[name="csrf-token"]')?.content;
const readOnlyDemo = document.body.dataset.readonly === 'true';
const escapeHtml = (value = '') => String(value).replace(/[&<>'"]/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' })[character]);
const stripHtml = (value = '') => { const element = document.createElement('div'); element.innerHTML = value; return element.textContent || ''; };
const formObject = form => Object.fromEntries(new FormData(form).entries());
const debounce = (callback, delay = 300) => { let timer; return (...args) => { clearTimeout(timer); timer = setTimeout(() => callback(...args), delay); }; };

async function request(url, options = {}) {
    const response = await fetch(url, { headers: { 'Accept': 'application/json', 'Content-Type': 'application/json', 'X-CSRF-TOKEN': csrf, ...(options.headers || {}) }, credentials: 'same-origin', ...options });
    const data = response.status === 204 ? {} : await response.json().catch(() => ({}));
    if (!response.ok) { const error = new Error(data.message || 'Something went wrong.'); error.errors = data.errors || {}; throw error; }
    return data;
}

function toast(message, isError = false) {
    const element = document.querySelector('#toast'); if (!element) return;
    element.textContent = message; element.classList.toggle('bg-red-950', isError); element.classList.remove('hidden');
    clearTimeout(toast.timer); toast.timer = setTimeout(() => element.classList.add('hidden'), 3200);
}

document.querySelectorAll('[data-theme-toggle]').forEach(button => button.addEventListener('click', () => {
    document.documentElement.classList.toggle('dark');
    localStorage.setItem('letrapress-theme', document.documentElement.classList.contains('dark') ? 'dark' : 'light');
}));

function initDirectory() {
    const app = document.querySelector('#directory-app'); if (!app) return;
    const form = document.querySelector('#directory-filters'); const results = document.querySelector('#directory-results'); const pagination = document.querySelector('#directory-pagination'); const count = document.querySelector('#directory-count'); const options = document.querySelector('#contact-options').innerHTML;
    const humanDialog = document.querySelector('#human-check-dialog'); const detailDialog = document.querySelector('#directory-detail-dialog'); const slider = document.querySelector('#human-slider'); const humanSubmit = humanDialog.querySelector('[data-human-submit]'); let pendingDetailId = null; let humanVerified = false;
    const safeUrl = value => { try { const parsed = new URL(value, window.location.origin); return ['http:', 'https:'].includes(parsed.protocol) ? parsed.href : ''; } catch { return ''; } };
    const renderCard = record => {
        const isJournalist = app.dataset.kind === 'journalist'; const name = isJournalist ? record.journalist_name : record.outlet_name; const image = isJournalist ? record.journalist_picture_url : record.outlet_picture_url; const role = isJournalist ? record.j_title?.title : record.j_media_types?.outlet_type; const location = [record.j_cities?.city, record.j_countries?.country].filter(Boolean).join(', '); const topics = (record.j_topics || []).slice(0, 3).map(topic => `<span class="badge">${escapeHtml(topic.topic)}</span>`).join('');
        const addControl = options ? `<div class="mt-5 flex gap-2 border-t border-stone-300 pt-4 dark:border-stone-700"><select class="field py-2 text-sm" aria-label="Contact list">${options}</select><button class="button-secondary shrink-0 px-3" type="button" data-add="${record.id}">Add</button></div>` : `<p class="mt-5 border-t border-stone-300 pt-4 text-sm dark:border-stone-700"><a class="button-quiet" href="/apps-contact-list-inbox">Create a contact list</a> to save this record.</p>`;
        const portrait = image ? `<img class="h-16 w-16 border border-stone-500 object-cover grayscale transition group-hover:grayscale-0" src="${escapeHtml(image)}" alt="View details for ${escapeHtml(name)}">` : `<span class="grid h-16 w-16 place-items-center border border-stone-500 bg-stone-200 text-2xl font-black text-stone-700 dark:bg-stone-800 dark:text-stone-200">${escapeHtml((name || '?').charAt(0))}</span>`;
        return `<article class="panel flex min-h-64 flex-col"><div class="grid grid-cols-[4rem_minmax(0,1fr)_4.5rem] items-start gap-4"><button class="group" type="button" data-detail-id="${record.id}" aria-label="View full details for ${escapeHtml(name)}">${portrait}</button><div class="min-w-0"><h2 class="break-words text-xl font-black leading-tight">${escapeHtml(name)}</h2><p class="mt-1 text-sm italic text-stone-600 dark:text-stone-300">${escapeHtml(role || 'Independent media')}</p><button class="button-quiet mt-2 text-xs" type="button" data-detail-id="${record.id}">View contact card</button></div><span class="w-[4.5rem] text-right text-sm font-black tabular-nums text-claret dark:text-red-300" title="Influence score">${escapeHtml(record.influence_score ?? '—')}</span></div><div class="mt-5 flex flex-1 flex-col"><p class="text-sm text-stone-600 dark:text-stone-300">${escapeHtml(location || 'Location not listed')}</p><div class="mt-4 flex flex-wrap gap-1.5">${topics || '<span class="badge">General</span>'}</div></div>${addControl}</article>`;
    };
    const detailField = (label, value, content = null) => `<div><p class="label">${escapeHtml(label)}</p>${content || `<p class="text-lg font-bold">${escapeHtml(value || 'Not listed')}</p>`}</div>`;
    const badgeList = (items, empty = 'Not listed') => items?.length ? items.map(item => `<span class="badge">${escapeHtml(item)}</span>`).join('') : `<span class="italic text-stone-500">${escapeHtml(empty)}</span>`;
    function renderDetails(record) {
        const email = record.email ? `<a class="button-quiet break-all" href="mailto:${escapeHtml(record.email)}">${escapeHtml(record.email)}</a>` : '<p class="italic text-stone-500">Not listed</p>';
        const website = safeUrl(record.website); const social = (record.social_links || []).map(link => { const url = safeUrl(link.url); return url ? `<a class="button-secondary px-3" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(link.type || 'Profile')}</a>` : ''; }).join('');
        const associated = record.kind === 'journalist' && record.outlet ? `<a class="button-quiet" href="${escapeHtml(safeUrl(record.outlet.outlet_url) || '#')}">${escapeHtml(record.outlet.outlet_name)}</a>` : record.kind === 'outlet' ? badgeList((record.journalists || []).map(item => `${item.name} · ${item.score ?? '—'}`), 'No linked journalists') : '<span class="italic text-stone-500">Not listed</span>';
        detailDialog.querySelector('[data-detail-kind]').textContent = record.kind === 'journalist' ? 'Journalist profile' : 'Media outlet'; detailDialog.querySelector('[data-detail-name]').textContent = record.name;
        detailDialog.querySelector('[data-detail-content]').innerHTML = `<div class="grid gap-5 border-y border-stone-400 py-6 sm:grid-cols-2 lg:grid-cols-3">${detailField('Role / format', record.title || record.media_type)}${detailField('Location', [record.city, record.state, record.country].filter(Boolean).join(', '))}${detailField('Influence score', record.score)}${detailField('Email', '', email)}${detailField('Phone', record.phone)}${record.kind === 'outlet' ? detailField('Website', '', website ? `<a class="button-quiet break-all" href="${escapeHtml(website)}" target="_blank" rel="noopener noreferrer">${escapeHtml(record.website)}</a>` : '<p class="italic text-stone-500">Not listed</p>') : ''}</div><div class="mt-6 grid gap-6 sm:grid-cols-2"><div><p class="label">Topics</p><div class="flex flex-wrap gap-2">${badgeList(record.topics)}</div></div><div><p class="label">Languages</p><div class="flex flex-wrap gap-2">${badgeList(record.languages)}</div></div><div><p class="label">Social media</p><div class="flex flex-wrap gap-2">${social || '<span class="italic text-stone-500">Not listed</span>'}</div></div><div><p class="label">${record.kind === 'journalist' ? 'Outlet' : 'Linked journalists'}</p><div class="flex flex-wrap gap-2">${associated}</div></div><div class="sm:col-span-2"><p class="label">Your contact lists</p><div class="flex flex-wrap gap-2">${badgeList(record.contact_lists, 'Not saved to a list')}</div></div></div>`;
        detailDialog.showModal();
    }
    async function fetchDetails(id) { try { const plural = app.dataset.kind === 'journalist' ? 'journalists' : 'outlets'; renderDetails(await request(`${app.dataset.detailBase}/${plural}/${id}`)); } catch (error) { toast(error.message, true); } }
    async function openDetails(id) { pendingDetailId = id; if (humanVerified) return fetchDetails(id); try { const status = await request(app.dataset.humanStatusUrl); humanVerified = status.verified; if (humanVerified) return fetchDetails(id); } catch (error) { toast(error.message, true); return; } slider.value = 0; humanSubmit.disabled = true; document.querySelector('#human-check-progress').textContent = '0%'; document.querySelector('#human-check-error').textContent = ''; humanDialog.showModal(); }
    async function load(url = null) {
        results.dataset.loading = 'true'; results.innerHTML = '<p class="col-span-full border-y border-stone-400 py-10 text-center italic">Consulting the directory…</p>';
        try { const query = new URLSearchParams(new FormData(form)); const data = await request(url || `${app.dataset.endpoint}?${query}`); count.textContent = data.records_total.toLocaleString(); results.innerHTML = data.data.length ? data.data.map(renderCard).join('') : '<p class="col-span-full border-y border-stone-400 py-10 text-center italic">No records match these filters.</p>'; pagination.innerHTML = `<button class="button-secondary" type="button" data-page-url="${escapeHtml(data.prev_page_url || '')}" ${data.prev_page_url ? '' : 'disabled'}>Previous</button><span class="text-sm font-bold">Page ${data.current_page} of ${data.last_page} · ${data.total.toLocaleString()} browsable</span><button class="button-secondary" type="button" data-page-url="${escapeHtml(data.next_page_url || '')}" ${data.next_page_url ? '' : 'disabled'}>Next</button>`; }
        catch (error) { results.innerHTML = `<p class="error-box col-span-full">${escapeHtml(error.message)}</p>`; } finally { results.dataset.loading = 'false'; }
    }
    form.addEventListener('change', () => load()); form.querySelector('[name="search"]').addEventListener('input', debounce(() => load())); pagination.addEventListener('click', event => { const url = event.target.closest('[data-page-url]')?.dataset.pageUrl; if (url) load(url); });
    results.addEventListener('click', async event => { const detail = event.target.closest('[data-detail-id]'); if (detail) return openDetails(detail.dataset.detailId); const button = event.target.closest('[data-add]'); if (!button) return; button.disabled = true; try { const data = await request(app.dataset.addUrl, { method: 'POST', body: JSON.stringify({ contact_list_id: button.previousElementSibling.value, kind: app.dataset.kind, record_id: button.dataset.add }) }); toast(data.message); } catch (error) { toast(error.message, true); } finally { button.disabled = false; } });
    slider.addEventListener('input', () => { const value = Number(slider.value); document.querySelector('#human-check-progress').textContent = `${value}%`; humanSubmit.disabled = value !== 100; });
    humanDialog.querySelector('[data-human-cancel]').addEventListener('click', () => humanDialog.close()); detailDialog.querySelector('[data-detail-close]').addEventListener('click', () => detailDialog.close());
    humanSubmit.addEventListener('click', async () => { humanSubmit.disabled = true; try { const result = await request(app.dataset.humanVerifyUrl, { method: 'POST', body: JSON.stringify({ slider: Number(slider.value) }) }); humanVerified = result.verified; humanDialog.close(); if (pendingDetailId) fetchDetails(pendingDetailId); } catch (error) { document.querySelector('#human-check-error').textContent = error.message; humanSubmit.disabled = false; } }); load();
}

function initContacts() {
    const app = document.querySelector('#contacts-app'); if (!app) return;
    const listArea = document.querySelector('#contact-lists'); const detail = document.querySelector('#contact-detail'); const search = document.querySelector('#contact-search'); const dialog = document.querySelector('#contact-dialog'); const memberDialog = document.querySelector('#contact-member-dialog'); const form = document.querySelector('#contact-form'); let lists = []; let selected = null;
    const renderLists = () => { const needle = search.value.toLowerCase(); const filtered = lists.filter(list => list.name.toLowerCase().includes(needle)); listArea.innerHTML = filtered.length ? filtered.map(list => `<button class="block w-full p-4 text-left hover:bg-stone-200 dark:hover:bg-stone-800 ${selected === list.id ? 'bg-stone-200 dark:bg-stone-800' : ''}" type="button" data-list-id="${list.id}"><span class="block font-black">${escapeHtml(list.name)}</span><span class="mt-1 block text-xs uppercase tracking-wider text-stone-500">${list.journalists_count} journalists · ${list.outlets_count} outlets</span></button>`).join('') : '<p class="p-5 italic text-stone-500">No contact lists yet.</p>'; };
    const memberRow = (member, kind) => { const name = kind === 'journalist' ? member.journalist_name : member.outlet_name; const note = kind === 'journalist' ? member.j_title?.title : member.j_media_types?.outlet_type; const payload = { kind, name, role: note || (kind === 'journalist' ? 'Journalist' : 'Media outlet'), country: member.j_countries?.country || 'Not listed', email: member.email || '', score: member.influence_score ?? '—', topics: (member.j_topics || []).map(topic => topic.topic) }; return `<li class="flex items-center justify-between gap-4 border-b border-stone-300 py-3 dark:border-stone-700"><button class="min-w-0 text-left" type="button" data-member='${escapeHtml(JSON.stringify(payload))}'><strong class="button-quiet text-base">${escapeHtml(name)}</strong><span class="mt-1 block text-sm italic text-stone-500">${escapeHtml(note || kind)} · View details</span></button><button class="button-secondary shrink-0 px-3" type="button" data-detach-kind="${kind}" data-detach-id="${member.id}">Remove</button></li>`; };
    function openMember(member) { memberDialog.querySelector('[data-member-kind]').textContent = member.kind === 'journalist' ? 'Journalist profile' : 'Outlet profile'; memberDialog.querySelector('[data-member-name]').textContent = member.name; memberDialog.querySelector('[data-member-details]').innerHTML = `<div><p class="label">Role / format</p><p class="text-lg font-bold">${escapeHtml(member.role)}</p></div><div><p class="label">Country</p><p class="text-lg font-bold">${escapeHtml(member.country)}</p></div><div><p class="label">Influence score</p><p class="text-lg font-bold tabular-nums text-claret dark:text-red-300">${escapeHtml(member.score)}</p></div><div><p class="label">Email</p>${member.email ? `<a class="button-quiet break-all" href="mailto:${escapeHtml(member.email)}">${escapeHtml(member.email)}</a>` : '<p class="italic text-stone-500">Not listed</p>'}</div><div class="sm:col-span-2"><p class="label">Topics</p><div class="flex flex-wrap gap-2">${member.topics.length ? member.topics.map(topic => `<span class="badge">${escapeHtml(topic)}</span>`).join('') : '<span class="italic text-stone-500">No topics listed</span>'}</div></div>`; memberDialog.showModal(); }
    async function loadLists() { try { lists = await request(app.dataset.indexUrl); renderLists(); if (selected && !lists.some(list => list.id === selected)) selected = null; } catch (error) { toast(error.message, true); } }
    async function showList(id) { selected = Number(id); renderLists(); detail.dataset.loading = 'true'; try { const list = await request(`${app.dataset.indexUrl}/${id}`); const members = [...list.journalists.map(item => memberRow(item, 'journalist')), ...list.outlets.map(item => memberRow(item, 'outlet'))].join(''); detail.innerHTML = `<div class="flex flex-wrap items-start justify-between gap-4 border-b-2 border-stone-800 pb-5 dark:border-stone-300"><div><p class="eyebrow">Contact list</p><h2 class="mt-2 text-3xl font-black">${escapeHtml(list.name)}</h2><p class="mt-2 max-w-2xl text-stone-600 dark:text-stone-300">${escapeHtml(list.description || 'No description.')}</p></div><div class="flex gap-3"><button class="button-secondary" type="button" data-edit-list='${escapeHtml(JSON.stringify({id:list.id,name:list.name,description:list.description || ''}))}'>Edit</button><button class="button-quiet text-red-800 dark:text-red-300" type="button" data-delete-list="${list.id}">Delete</button></div></div><h3 class="mt-6 text-sm font-bold uppercase tracking-[.14em]">${list.journalists.length + list.outlets.length} saved contacts</h3><ul class="mt-3">${members || '<li class="py-8 text-center italic text-stone-500">Add journalists or outlets from the directory.</li>'}</ul>`; } catch (error) { detail.innerHTML = `<p class="error-box">${escapeHtml(error.message)}</p>`; } finally { detail.dataset.loading = 'false'; } }
    function openForm(list = null) { form.reset(); form.elements.id.value = list?.id || ''; form.elements.name.value = list?.name || ''; form.elements.description.value = list?.description || ''; dialog.querySelector('[data-modal-title]').textContent = list ? 'Edit contact list' : 'New contact list'; document.querySelector('#contact-errors').textContent = readOnlyDemo ? 'Demo mode: you can try the form, but saving is disabled.' : ''; dialog.showModal(); }
    document.querySelector('[data-contact-create]').addEventListener('click', () => openForm()); dialog.querySelector('[data-dialog-close]').addEventListener('click', () => dialog.close()); memberDialog.querySelector('[data-member-close]').addEventListener('click', () => memberDialog.close()); search.addEventListener('input', renderLists); listArea.addEventListener('click', event => { const button = event.target.closest('[data-list-id]'); if (button) showList(button.dataset.listId); });
    detail.addEventListener('click', async event => { const member = event.target.closest('[data-member]'); if (member) return openMember(JSON.parse(member.dataset.member)); const edit = event.target.closest('[data-edit-list]'); if (edit) return openForm(JSON.parse(edit.dataset.editList)); const remove = event.target.closest('[data-detach-id]'); if (remove) { try { const data = await request(`${app.dataset.indexUrl}/${selected}/member`, { method: 'DELETE', body: JSON.stringify({ kind: remove.dataset.detachKind, record_id: remove.dataset.detachId }) }); toast(data.message); await Promise.all([showList(selected), loadLists()]); } catch (error) { toast(error.message, true); } return; } const deletion = event.target.closest('[data-delete-list]'); if (deletion && confirm('Delete this contact list?')) { try { const data = await request(`${app.dataset.indexUrl}/${deletion.dataset.deleteList}`, { method: 'DELETE' }); toast(data.message); selected = null; detail.innerHTML = '<div class="grid min-h-64 place-items-center text-center"><p class="italic">Choose another list.</p></div>'; loadLists(); } catch (error) { toast(error.message, true); } } });
    form.addEventListener('submit', async event => { event.preventDefault(); const payload = formObject(form); const id = payload.id; delete payload.id; try { const data = await request(id ? `${app.dataset.indexUrl}/${id}` : app.dataset.indexUrl, { method: id ? 'PUT' : 'POST', body: JSON.stringify(payload) }); toast(data.message); dialog.close(); await loadLists(); if (id) showList(id); } catch (error) { document.querySelector('#contact-errors').textContent = Object.values(error.errors || {}).flat().join(' ') || error.message; } }); loadLists();
}

function initReleases() {
    const app = document.querySelector('#releases-app'); if (!app) return; const rows = document.querySelector('#release-rows'); const pagination = document.querySelector('#release-pagination');
    async function load(url = null) { const params = new URLSearchParams({ search: document.querySelector('#release-search').value, folder_id: document.querySelector('#release-folder-filter').value }); try { const data = await request(url || `${app.dataset.indexUrl}?${params}`); rows.innerHTML = data.data.length ? data.data.map(item => `<tr><td class="p-4"><strong>${escapeHtml(item.subject)}</strong><p class="mt-1 max-w-md truncate text-sm text-stone-500">${escapeHtml(stripHtml(item.content))}</p></td><td class="p-4"><span class="badge">${escapeHtml(item.distribution || 'newsroom')}</span><span class="mt-2 block text-xs italic">${escapeHtml(item.release_type || 'release')}</span></td><td class="p-4 text-sm font-bold tabular-nums">${Number(item.recipient_count || 0).toLocaleString()}</td><td class="p-4"><span class="badge">${escapeHtml(item.status || 'draft')}</span></td><td class="p-4 text-sm">${new Date(item.updated_at).toLocaleDateString()}</td><td class="p-4"><div class="flex justify-end gap-3"><a class="button-secondary px-3" href="${app.dataset.editBase}/${item.id}/edit">Edit</a><button class="button min-h-10 border-red-800 bg-red-900 px-3 text-white hover:bg-red-800" type="button" data-release-delete="${item.id}">Delete</button></div></td></tr>`).join('') : '<tr><td class="p-10 text-center italic" colspan="6">No pitches or releases in this drawer.</td></tr>'; pagination.innerHTML = paginationHtml(data); } catch (error) { toast(error.message, true); } }
    document.querySelector('#release-search').addEventListener('input', debounce(() => load())); document.querySelector('#release-folder-filter').addEventListener('change', () => load()); pagination.addEventListener('click', event => { const url = event.target.closest('[data-page-url]')?.dataset.pageUrl; if (url) load(url); });
    rows.addEventListener('click', async event => { const deletion = event.target.closest('[data-release-delete]'); if (deletion && confirm('Delete this pitch or release?')) { try { const data = await request(`${app.dataset.indexUrl}/${deletion.dataset.releaseDelete}`, { method: 'DELETE' }); toast(data.message); load(); } catch (error) { toast(error.message, true); } } }); load();
}

function initReleaseEditor() {
    const app = document.querySelector('#release-editor'); if (!app) return;
    const form = document.querySelector('#release-editor-form'); const content = form.elements.content; const subject = form.elements.subject; const analysisArea = document.querySelector('#release-analysis'); const recommendationsArea = document.querySelector('#release-recommendations'); const errors = document.querySelector('#release-editor-errors'); const recipientPanel = document.querySelector('[data-recipient-panel]');
    const humanDialog = document.querySelector('#recommendation-human-dialog'); const detailDialog = document.querySelector('#recommendation-detail-dialog'); const slider = document.querySelector('#recommendation-human-slider'); const humanSubmit = humanDialog.querySelector('[data-recommendation-human-submit]'); let pendingDetail = null; let humanVerified = false;
    let analysis = JSON.parse(document.querySelector('#release-analysis-data').textContent || 'null'); const selected = new Map();
    (JSON.parse(document.querySelector('#release-recipient-data').textContent || '[]') || []).forEach(item => selected.set(`${item.type}-${item.id}`, item));
    const updateWordCount = () => document.querySelector('[data-word-count]').textContent = stripHtml(content.value).trim().split(/\s+/).filter(Boolean).length;
    const updateRecipientCount = () => { document.querySelector('[data-recipient-count]').textContent = selected.size; document.querySelectorAll('[data-recipient-type][data-recipient-id]').forEach(input => { input.checked = selected.has(`${input.dataset.recipientType}-${input.dataset.recipientId}`); }); };
    const updateDistribution = () => { const distribution = form.elements.distribution.value; recipientPanel.classList.toggle('opacity-50', distribution === 'newsroom'); recipientPanel.querySelectorAll('input').forEach(input => input.disabled = distribution === 'newsroom'); };
    function renderAnalysis() { if (!analysis) { analysisArea.innerHTML = '<p class="italic text-stone-500">Run the analysis when your draft has enough detail.</p>'; return; } analysisArea.innerHTML = `<p class="leading-7">${escapeHtml(analysis.summary || '')}</p><div class="mt-5"><p class="label">Extracted keywords</p><div class="flex flex-wrap gap-2">${(analysis.keywords || []).map(keyword => `<span class="badge">${escapeHtml(keyword)}</span>`).join('')}</div></div><div class="mt-5"><p class="label">Possible media angles</p><ul class="list-disc space-y-2 pl-5">${(analysis.media_angles || []).map(angle => `<li>${escapeHtml(angle)}</li>`).join('')}</ul></div>`; }
    const safeUrl = value => { try { const parsed = new URL(value, window.location.origin); return ['http:', 'https:'].includes(parsed.protocol) ? parsed.href : ''; } catch { return ''; } };
    const detailField = (label, value, inner = null) => `<div><p class="label">${escapeHtml(label)}</p>${inner || `<p class="text-lg font-bold">${escapeHtml(value || 'Not listed')}</p>`}</div>`;
    const badgeList = (items, empty = 'Not listed') => items?.length ? items.map(item => `<span class="badge">${escapeHtml(item)}</span>`).join('') : `<span class="italic text-stone-500">${escapeHtml(empty)}</span>`;
    function recommendationCard(item) {
        const key = `${item.kind}-${item.id}`; const picture = safeUrl(item.picture_url); const initial = escapeHtml((item.name || '?').charAt(0));
        const portrait = picture ? `<img class="h-20 w-20 border border-stone-500 object-cover grayscale transition hover:grayscale-0" src="${escapeHtml(picture)}" alt="${escapeHtml(item.name)}">` : `<span class="grid h-20 w-20 place-items-center border border-stone-500 bg-stone-200 text-2xl font-black text-stone-700 dark:bg-stone-800 dark:text-stone-200">${initial}</span>`;
        return `<article class="border border-stone-400 p-4 has-[:checked]:border-claret has-[:checked]:bg-red-50 dark:border-stone-700 dark:has-[:checked]:bg-red-950/40"><div class="grid grid-cols-[5rem_minmax(0,1fr)] gap-4"><button class="group" type="button" data-recommendation-detail data-kind="${item.kind}" data-id="${item.id}" aria-label="View full details for ${escapeHtml(item.name)}">${portrait}</button><div class="min-w-0"><div class="flex items-start justify-between gap-3"><strong class="leading-tight">${escapeHtml(item.name)}</strong><span class="shrink-0 text-sm font-black tabular-nums text-claret dark:text-red-300">${item.match_score}%</span></div><p class="mt-1 text-sm italic text-stone-500">${escapeHtml([item.role, item.country].filter(Boolean).join(' · '))}</p><button class="button-quiet mt-2 text-xs" type="button" data-recommendation-detail data-kind="${item.kind}" data-id="${item.id}">View details</button></div></div><p class="mt-3 text-xs">${escapeHtml(item.match_reason)}</p><label class="mt-3 flex cursor-pointer items-center gap-2 border-t border-stone-300 pt-3 text-sm font-bold dark:border-stone-700"><input class="text-claret focus:ring-claret" type="checkbox" data-recipient-type="${item.kind}" data-recipient-id="${item.id}" data-recipient-score="${item.match_score}" data-recipient-reason="${escapeHtml(item.match_reason)}" ${selected.has(key) ? 'checked' : ''}> Select recipient</label></article>`;
    }
    function renderRecommendationDetails(record) {
        const email = record.email ? `<a class="button-quiet break-all" href="mailto:${escapeHtml(record.email)}">${escapeHtml(record.email)}</a>` : '<p class="italic text-stone-500">Not listed</p>';
        const website = safeUrl(record.website); const social = (record.social_links || []).map(link => { const url = safeUrl(link.url); return url ? `<a class="button-secondary px-3" href="${escapeHtml(url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(link.type || 'Profile')}</a>` : ''; }).join('');
        const associated = record.kind === 'journalist' && record.outlet ? `<a class="button-quiet" href="${escapeHtml(safeUrl(record.outlet.outlet_url) || '#')}">${escapeHtml(record.outlet.outlet_name)}</a>` : record.kind === 'outlet' ? badgeList((record.journalists || []).map(item => `${item.name} · ${item.score ?? '—'}`), 'No linked journalists') : '<span class="italic text-stone-500">Not listed</span>';
        detailDialog.querySelector('[data-recommendation-detail-kind]').textContent = record.kind === 'journalist' ? 'Journalist profile' : 'Media outlet'; detailDialog.querySelector('[data-recommendation-detail-name]').textContent = record.name;
        detailDialog.querySelector('[data-recommendation-detail-content]').innerHTML = `<div class="grid gap-5 border-y border-stone-400 py-6 sm:grid-cols-2 lg:grid-cols-3">${detailField('Role / format', record.title || record.media_type)}${detailField('Location', [record.city, record.state, record.country].filter(Boolean).join(', '))}${detailField('Influence score', record.score)}${detailField('Email', '', email)}${detailField('Phone', record.phone)}${record.kind === 'outlet' ? detailField('Website', '', website ? `<a class="button-quiet break-all" href="${escapeHtml(website)}" target="_blank" rel="noopener noreferrer">${escapeHtml(record.website)}</a>` : '<p class="italic text-stone-500">Not listed</p>') : ''}</div><div class="mt-6 grid gap-6 sm:grid-cols-2"><div><p class="label">Topics</p><div class="flex flex-wrap gap-2">${badgeList(record.topics)}</div></div><div><p class="label">Languages</p><div class="flex flex-wrap gap-2">${badgeList(record.languages)}</div></div><div><p class="label">Social media</p><div class="flex flex-wrap gap-2">${social || '<span class="italic text-stone-500">Not listed</span>'}</div></div><div><p class="label">${record.kind === 'journalist' ? 'Outlet' : 'Linked journalists'}</p><div class="flex flex-wrap gap-2">${associated}</div></div><div class="sm:col-span-2"><p class="label">Your contact lists</p><div class="flex flex-wrap gap-2">${badgeList(record.contact_lists, 'Not saved to a list')}</div></div></div>`;
        detailDialog.showModal();
    }
    async function fetchRecommendationDetails(kind, id) { try { renderRecommendationDetails(await request(`${app.dataset.detailBase}/${kind === 'journalist' ? 'journalists' : 'outlets'}/${id}`)); } catch (error) { toast(error.message, true); } }
    async function openRecommendationDetails(kind, id) { pendingDetail = { kind, id }; if (humanVerified) return fetchRecommendationDetails(kind, id); try { const status = await request(app.dataset.humanStatusUrl); humanVerified = status.verified; if (humanVerified) return fetchRecommendationDetails(kind, id); } catch (error) { toast(error.message, true); return; } slider.value = 0; humanSubmit.disabled = true; document.querySelector('#recommendation-human-progress').textContent = '0%'; document.querySelector('#recommendation-human-error').textContent = ''; humanDialog.showModal(); }
    function renderRecommendations(data) { const topics = data.matched_topics || []; recommendationsArea.innerHTML = `<div class="border-t border-stone-400 pt-6"><div class="flex flex-wrap items-end justify-between gap-3"><div><p class="label">Database topics used</p><div class="flex flex-wrap gap-2">${topics.length ? topics.map(topic => `<span class="badge">${escapeHtml(topic.topic)} · ${topic.score}%</span>`).join('') : '<span class="italic text-stone-500">No close database topics found.</span>'}</div></div><p class="text-sm italic">Choose only genuinely relevant contacts.</p></div><div class="mt-6 grid gap-6 lg:grid-cols-2"><div><h3 class="text-xl font-black">Recommended journalists</h3><div class="mt-3 space-y-3">${(data.journalists || []).map(recommendationCard).join('') || '<p class="italic text-stone-500">No journalist matches yet.</p>'}</div></div><div><h3 class="text-xl font-black">Recommended outlets</h3><div class="mt-3 space-y-3">${(data.outlets || []).map(recommendationCard).join('') || '<p class="italic text-stone-500">No outlet matches yet.</p>'}</div></div></div></div>`; updateRecipientCount(); }
    recommendationsArea.addEventListener('click', event => { const trigger = event.target.closest('[data-recommendation-detail]'); if (trigger) openRecommendationDetails(trigger.dataset.kind, trigger.dataset.id); });
    slider.addEventListener('input', () => { const value = Number(slider.value); document.querySelector('#recommendation-human-progress').textContent = `${value}%`; humanSubmit.disabled = value !== 100; });
    humanDialog.querySelector('[data-recommendation-human-cancel]').addEventListener('click', () => humanDialog.close());
    detailDialog.querySelector('[data-recommendation-detail-close]').addEventListener('click', () => detailDialog.close());
    humanSubmit.addEventListener('click', async () => { humanSubmit.disabled = true; try { const result = await request(app.dataset.humanVerifyUrl, { method: 'POST', body: JSON.stringify({ slider: Number(slider.value) }) }); humanVerified = result.verified; humanDialog.close(); if (pendingDetail) fetchRecommendationDetails(pendingDetail.kind, pendingDetail.id); } catch (error) { document.querySelector('#recommendation-human-error').textContent = error.message; humanSubmit.disabled = false; } });
    form.addEventListener('change', event => { const input = event.target.closest('[data-recipient-type][data-recipient-id]'); if (input) { const item = { type: input.dataset.recipientType, id: Number(input.dataset.recipientId), source: input.dataset.recipientType === 'list' ? 'manual' : 'ai', score: input.dataset.recipientScore ? Number(input.dataset.recipientScore) : null, reason: input.dataset.recipientReason || null }; input.checked ? selected.set(`${item.type}-${item.id}`, item) : selected.delete(`${item.type}-${item.id}`); updateRecipientCount(); } if (event.target.name === 'distribution') updateDistribution(); });
    content.addEventListener('input', updateWordCount);
    document.querySelector('[data-release-analyze]').addEventListener('click', async event => { const button = event.currentTarget; errors.textContent = ''; button.disabled = true; button.textContent = 'Analyzing…'; try { const data = await request(app.dataset.analyzeUrl, { method: 'POST', body: JSON.stringify({ subject: subject.value, content: content.value }) }); analysis = data.analysis; if (analysis.release_type) form.elements.release_type.value = analysis.release_type; renderAnalysis(); renderRecommendations(data.recommendations); toast('Analysis complete.'); } catch (error) { errors.textContent = Object.values(error.errors || {}).flat().join(' ') || error.message; } finally { button.disabled = false; button.textContent = 'Analyze copy'; } });
    form.addEventListener('submit', async event => { event.preventDefault(); errors.textContent = ''; const button = form.querySelector('[type="submit"]'); button.disabled = true; const payload = { subject: subject.value, content: content.value, folder_id: Number(form.elements.folder_id.value), release_type: form.elements.release_type.value, distribution: form.elements.distribution.value, template_key: form.elements.template_key.value, analysis, recipients: [...selected.values()] }; try { const data = await request(app.dataset.saveUrl, { method: app.dataset.saveMethod, body: JSON.stringify(payload) }); toast(data.message); document.querySelector('[data-save-state]').textContent = data.data.status; if (data.redirect) window.location.href = data.redirect; } catch (error) { errors.textContent = Object.values(error.errors || {}).flat().join(' ') || error.message; } finally { button.disabled = false; } });
    document.querySelector('[data-release-save]').addEventListener('click', () => form.requestSubmit()); renderAnalysis(); updateWordCount(); updateRecipientCount(); updateDistribution();
}

const paginationHtml = data => `<div class="flex justify-between"><button class="button-secondary" data-page-url="${escapeHtml(data.prev_page_url || '')}" ${data.prev_page_url ? '' : 'disabled'}>Previous</button><span class="self-center text-sm font-bold">Page ${data.current_page} of ${data.last_page}</span><button class="button-secondary" data-page-url="${escapeHtml(data.next_page_url || '')}" ${data.next_page_url ? '' : 'disabled'}>Next</button></div>`;

function initNewsrooms() {
    const app = document.querySelector('#newsrooms-app'); if (!app) return; const cards = document.querySelector('#room-cards'); const dialog = document.querySelector('#room-dialog'); const form = document.querySelector('#room-form'); const pagination = document.querySelector('#room-pagination'); const records = new Map();
    async function load(url = null) { const params = new URLSearchParams({ search: document.querySelector('#room-search').value }); try { const data = await request(url || `${app.dataset.indexUrl}?${params}`); records.clear(); data.data.forEach(item => records.set(item.id, item)); cards.innerHTML = data.data.length ? data.data.map(item => `<article class="panel flex flex-col">${item.featured_image ? `<img class="mb-5 aspect-[16/8] w-full border border-stone-500 object-cover grayscale" src="${escapeHtml(item.featured_image)}" alt="">` : ''}<p class="eyebrow">${escapeHtml(item.date || 'Undated')} · ${escapeHtml(item.folder?.folder_name || 'Unfiled')}</p><h2 class="mt-2 text-2xl font-black">${escapeHtml(item.subject)}</h2><p class="mt-3 flex-1 leading-6 text-stone-600 dark:text-stone-300">${escapeHtml(item.summary || stripHtml(item.content).slice(0, 150))}</p><div class="mt-5 flex flex-wrap items-center gap-3 border-t border-stone-300 pt-4 dark:border-stone-700">${item.folder?.folder_name === 'Go Public' ? `<a class="button-secondary mr-auto px-3" href="${app.dataset.publicBase}/${item.id}" target="_blank">View public</a>` : '<span class="mr-auto"></span>'}<button class="button-secondary px-3" type="button" data-room-edit="${item.id}">Edit</button><button class="button min-h-10 border-red-800 bg-red-900 px-3 text-white hover:bg-red-800" type="button" data-room-delete="${item.id}">Delete</button></div></article>`).join('') : '<p class="col-span-full border-y border-stone-400 py-10 text-center italic">No newsroom stories yet.</p>'; pagination.innerHTML = paginationHtml(data); } catch (error) { toast(error.message, true); } }
    function openForm(item = null) { form.reset(); form.elements.id.value = item?.id || ''; ['subject','summary','featured_image','content','date'].forEach(field => form.elements[field].value = item?.[field] || ''); if (item) form.elements.folder_id.value = item.folder_id; dialog.querySelector('[data-modal-title]').textContent = item ? 'Revise newsroom story' : 'New newsroom story'; document.querySelector('#room-errors').textContent = readOnlyDemo ? 'Demo mode: you can edit this story, but saving is disabled.' : ''; dialog.showModal(); }
    document.querySelector('[data-room-create]').addEventListener('click', () => openForm()); dialog.querySelector('[data-dialog-close]').addEventListener('click', () => dialog.close()); document.querySelector('#room-search').addEventListener('input', debounce(() => load())); pagination.addEventListener('click', event => { const url = event.target.closest('[data-page-url]')?.dataset.pageUrl; if (url) load(url); });
    cards.addEventListener('click', async event => { const edit = event.target.closest('[data-room-edit]'); if (edit) return openForm(records.get(Number(edit.dataset.roomEdit))); const deletion = event.target.closest('[data-room-delete]'); if (deletion && confirm('Delete this newsroom story?')) { try { const data = await request(`${app.dataset.indexUrl}/${deletion.dataset.roomDelete}`, { method: 'DELETE' }); toast(data.message); load(); } catch (error) { toast(error.message, true); } } });
    form.addEventListener('submit', async event => { event.preventDefault(); const payload = formObject(form); const id = payload.id; delete payload.id; try { const data = await request(id ? `${app.dataset.indexUrl}/${id}` : app.dataset.indexUrl, { method: id ? 'PUT' : 'POST', body: JSON.stringify(payload) }); toast(data.message); dialog.close(); load(); } catch (error) { document.querySelector('#room-errors').textContent = Object.values(error.errors || {}).flat().join(' ') || error.message; } }); load();
}

initDirectory(); initContacts(); initReleases(); initReleaseEditor(); initNewsrooms();
